### ISSUE TITLE
getting FileNotFoundException in library 

### ISSUE THREAD

**Issue by nikhilgarg89** [stealthcopter/AndroidNetworkTools#47] opened 2018-07-30 06:15 UTC
W/System.err: java.io.FileNotFoundException: /proc/net/arp: open failed: EMFILE (Too many open files)
        at libcore.io.IoBridge.open(IoBridge.java:452)
        at java.io.FileInputStream.<init>(FileInputStream.java:76)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at java.io.FileReader.<init>(FileReader.java:66)
        at com.stealthcopter.networktools.ARPInfo.getLinesInARPCache(ARPInfo.java:126)
        at com.stealthcopter.networktools.ARPInfo.getMACFromIPAddress(ARPInfo.java:38)
        at com.stealthcopter.networktools.SubnetDevices$SubnetDeviceFinderRunnable.run(SubnetDevices.java:183)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EMFILE (Too many open files)
07-30 11:42:51.902 8612-8750/com.test.ping W/System.err:     at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:438)
    	... 9 more
07-30 11:42:52.091 8612-8844/com.test.ping W/art: Large object allocation failed: ashmem_create_region failed for 'large object space allocation': Too many open files

**Comment by stealthcopter** [comment] 2018-08-13 15:57
I believe this is caused by us checking `/proc/net/arp` for the mac address each time a device is found. If there are many devices on the network it will result in wasteful re-reading. I will implement a method of caching it to prevent this error from occurring in the next build.

**Comment by stealthcopter** [comment] 2018-08-14 09:01
Fixed in 0.4.3

**Closed by stealthcopter** 2018-08-14 09:01 UTC
Labels: bug
