### ISSUE TITLE
Getting FileNotFoundException on android 10

### ISSUE THREAD

**Issue by radheyshyamjat** [stealthcopter/AndroidNetworkTools#70] opened 2020-04-15 07:02 UTC
java.io.FileNotFoundException: /proc/net/arp: open failed: EACCES (Permission denied)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:159)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:115)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at java.io.FileReader.<init>(FileReader.java:58)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at com.stealthcopter.networktools.ARPInfo.getLinesInARPCache(ARPInfo.java:126)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at com.stealthcopter.networktools.ARPInfo.getAllIPAndMACAddressesInARPCache(ARPInfo.java:104)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at com.stealthcopter.networktools.SubnetDevices$1.run(SubnetDevices.java:188)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at libcore.io.Linux.open(Native Method)
2020-04-15 12:23:35.039 23238-23295/app.ping W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2020-04-15 12:23:35.040 23238-23295/app.ping W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
2020-04-15 12:23:35.040 23238-23295/app.ping W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2020-04-15 12:23:35.040 23238-23295/app.ping W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
2020-04-15 12:23:35.040 23238-23295/app.ping W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:482)

**Comment by stealthcopter** [comment] 2020-04-15 08:50
@radheyshyamjat Sorry about that, this is fixed in the latest source code but I need to push out a new release, I'll get that done today!

**Comment by stealthcopter** [comment] 2020-04-15 09:04
Should be resolved by updating to the latest library version 0.4.5.3

**Closed by stealthcopter** 2020-04-15 09:04 UTC

**Comment by radheyshyamjat** [comment] 2020-04-15 09:10
Thanks @stealthcopter providing instant reply

**Comment by YoannHe** [comment] 2020-10-15 17:19
Hello,
I have the same error as well, FileNotFoundException for /proc/net/arp
There is no fix for Android 10 ?

**Comment by momilc** [comment] 2020-10-26 00:30
Me too !!

**Comment by xiandanin** [comment] 2021-01-29 03:03
I am using 0.4.5.3, but this problem still occurs

```
implementation 'com.github.stealthcopter:AndroidNetworkTools:0.4.5.3'
```

```
java.io.FileNotFoundException: /proc/net/arp: open failed: EACCES (Permission denied)
    at libcore.io.IoBridge.open(IoBridge.java:496)
    at java.io.FileInputStream.<init>(FileInputStream.java:159)
    at java.io.FileInputStream.<init>(FileInputStream.java:115)
    at java.io.FileReader.<init>(FileReader.java:58)
    at com.stealthcopter.networktools.ARPInfo.getLinesInARPCache(ARPInfo.java:125)
    at com.stealthcopter.networktools.ARPInfo.getAllIPAndMACAddressesInARPCache(ARPInfo.java:101)
    at com.stealthcopter.networktools.SubnetDevices$1.run(SubnetDevices.java:166)
    at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
    at libcore.io.Linux.open(Native Method)
    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7459)
    at libcore.io.IoBridge.open(IoBridge.java:482)
	... 7 more
```

**Comment by jayesh83** [comment] 2021-02-05 09:49
Yes! The issue is intact. @stealthcopter Can you please check that out once again?

**Comment by Jack-Overflow** [comment] 2021-04-21 16:48
This is still an issue.
